name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build-push-docker-image: 
    name: Build and push image to GH packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: RHV044
          password: ${{ secrets.GH_Registry_Access_Token }}

      - name: Build and push new image
        run: |
          docker build -t ghcr.io/utn-pfinal-g104/pictogar-api:latest .
          docker push ghcr.io/utn-pfinal-g104/pictogar-api:latest
  deploy-over-ssh:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build-push-docker-image
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd pictogar && sudo docker-compose pull && sudo docker-compose up -d --no-deps pictogar-api
          host: 20.115.17.201
          username: pictogar-user
          password: ${{ secrets.SSH_SERVER_PASSWORD }}

